apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    app: jenkins
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: gcr.io/stacksmith-images/jenkins-redmine-demo
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: docker-cfg
          mountPath: /root/.dockercfg
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: docker-bin
          mountPath: /usr/bin/docker
        - name: kubectl
          mountPath: /usr/local/bin/kubectl
        - name: jenkins-persistent-storage
          mountPath: /var/jenkins_home
      volumes:
      - name: docker-cfg
        hostPath:
          path: /root/.dockercfg
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: docker-bin
        hostPath:
          path: /usr/bin/docker
      - name: kubectl
        hostPath:
          path: /usr/local/bin/kubectl
      - name: jenkins-persistent-storage
        gcePersistentDisk:
          pdName: stacksmith-redmine-jenkins
          fsType: ext4
