apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  replicas: 1
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
        - name: jenkins
          image: lachlanevenson/k8s-kubectl
          command: ["tail", "-f", "/etc/lsb_release"]
          volumeMounts:
            - name: jenkins-service-account
              mountPath: /etc/jenkins-service-account
              readOnly: true
      volumes:
        - name: jenkins-service-account
          secret:
            secretName: jenkins-token-daj5e
