apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  labels:
    name: mariadb-slave
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    name: mariadb-slave
