apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb-master
  labels:
    name: mariadb-master
spec:
  replicas: 1
  selector:
    name: mariadb-master
  template:
    metadata:
      labels:
        name: mariadb-master
    spec:
      containers:
        - name: mariadb-master
          image: bitnami/mariadb:5.5.46-0-r01
          args:
            - --max_connect_errors=1000
          env:
            - name: MARIADB_DATABASE
              value: redmine_production
            - name: MARIADB_USER
              value: redmine
            - name: MARIADB_PASSWORD
              value: secretpassword
            - name: MARIADB_REPLICATION_MODE
              value: master
            - name: MARIADB_REPLICATION_USER
              value: replication
            - name: MARIADB_REPLICATION_PASSWORD
              value: secretpassword
          ports:
            - containerPort: 3306
              name: mariadb-master
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /bitnami/mariadb/data
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
      volumes:
        - name: mariadb-persistent-storage
          gcePersistentDisk:
            pdName: mariadb-disk
            fsType: ext4
